all:	
	@echo "*********************************************** "
	@echo "********* BUILDING PHYLOSCAN C LIBRARY ******** "
	@echo "*********************************************** "			
	MAKEFLAGS="SHLIB_CXXLD=g++ CXX=g++" R CMD SHLIB -o phyloscan.so *.cpp
		